server:
 port: 9300
 context-path: /group
httpServer:
  case:
    baseUrl: http://127.0.0.1:9200
    runPath: /case/group/execute
    getCasePath:
  user:
    baseUrl: http://127.0.0.1:9090
    roleUrlpath: /user/getRoleUrlPathBySystem?system=group

spring:
  redis:
    host: 192.168.1.121
    port: 6379
    timeout: 20000

  datasource:
    url: jdbc:mysql://192.168.1.121:3306/testingplatform?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Imobpay123456!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    naming:
#      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

ignore:
  urlPath:
  ip: 127.0.0.1

