server:
 port: 9090
 context-path: /group
httpServer:
  case:
    baseUrl: http://192.168.1.49:9090
    runPath: /case/group/execute
    getCasePath:
  user:
    baseUrl: http://192.168.32.44:9090
    roleUrlpath: /user/getRoleUrlPathBySystem?system=group

spring:
  redis:
    host: 192.168.1.46
    port: 6379
    timeout: 20000

  datasource:
    url: jdbc:mysql://192.168.1.42:3306/testingplatform?useUnicode=true&amp;characterEncoding=utf-8
    username: tester
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    naming:
#      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

ignore:
  urlPath:
  ip: 192.168.1.43,192.168.1.44,192.168.1.47,192.168.1.49

